#!/usr/bin/env python3
# Copyright 2026 bong-water-water-bong
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Embeds HIP code objects (raw AMDGPU ELF, one per .hip stem and target) as a C++ table.

usage: embed_hip_code_objects.py OUTPUT.inc STEM:TARGET:PATH ...
"""

import hashlib
import sys


def main() -> int:
    out_path, entries = sys.argv[1], sys.argv[2:]
    lines = ["// Generated by embed_hip_code_objects.py. Do not edit.", ""]
    table = []
    for index, entry in enumerate(entries):
        stem, target, path = entry.split(":", 2)
        data = open(path, "rb").read()
        if data[:4] != b"\x7fELF":
            print(f"{path}: not a raw ELF code object (offload bundle?)", file=sys.stderr)
            return 1
        digest = hashlib.sha256(data).hexdigest()[:16]
        lines.append(f"static const unsigned char kHipCodeObject{index}[] = {{")
        for offset in range(0, len(data), 24):
            lines.append("    " + ",".join(str(b) for b in data[offset:offset + 24]) + ",")
        lines.append("};")
        table.append(f'    {{ "{stem}", "{target}", kHipCodeObject{index}, sizeof(kHipCodeObject{index}), "{digest}" }},')
    lines.append("static const HipEmbeddedCodeObject kHipEmbeddedCodeObjects[] = {")
    lines.extend(table)
    lines.append("    { nullptr, nullptr, nullptr, 0, nullptr },")
    lines.append("};")
    text = "\n".join(lines) + "\n"
    try:
        if open(out_path).read() == text:
            return 0
    except OSError:
        pass
    open(out_path, "w").write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
