// Copyright 2026 bong-water-water-bong
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "hip/hip-code-objects.h"

#include <cstring>

namespace ggml::hrx {
namespace {

struct HipEmbeddedCodeObject {
    const char *          stem;
    const char *          target;
    const unsigned char * data;
    size_t                size;
    const char *          digest;
};

// Generated by hip/embed_hip_code_objects.py: kHipEmbeddedCodeObjects, terminated by a null stem.
#include "ggml-hrx-hip-code-objects.inc"

const HipEmbeddedCodeObject * find_code_object(const char * stem, const char * target) {
    if (stem == nullptr) {
        return nullptr;
    }
    for (const HipEmbeddedCodeObject * object = kHipEmbeddedCodeObjects; object->stem != nullptr; ++object) {
        if (std::strcmp(object->stem, stem) == 0 && (target == nullptr || std::strcmp(object->target, target) == 0)) {
            return object;
        }
    }
    return nullptr;
}

}  // namespace

const void * hip_code_object_data(const char * stem, const char * target, size_t * size) {
    const HipEmbeddedCodeObject * object = find_code_object(stem, target);
    if (size != nullptr) {
        *size = object != nullptr ? object->size : 0;
    }
    return object != nullptr ? object->data : nullptr;
}

bool hip_code_object_embedded(const char * stem) {
    return find_code_object(stem, nullptr) != nullptr;
}

const char * hip_code_object_digest(const char * stem) {
    const HipEmbeddedCodeObject * object = find_code_object(stem, nullptr);
    return object != nullptr ? object->digest : nullptr;
}

}  // namespace ggml::hrx
